[package]
name = "token"
version = "0.0.1"
authors = []

[dependencies]
rustc-serialize = "*"

[dependencies.openssl]
version = "*"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"